- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  vars:
    home: "{{ ansible_env.HOME }}"
  tasks:
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - "{{ home }}/.local/bin"
    - name: Copy alok.jar to ~/.local/bin
      copy:
        src: ../target/alok-1.0-SNAPSHOT-jar-with-dependencies.jar
        dest: "{{ home }}/.local/bin/alok.jar"
        mode: "0644"
    - name: Create systemd service (user scope)
      copy:
        src: alok.service
        dest: "{{ home }}/.config/systemd/user/alok.service"
    - name: Enable & (re)start alok service
      systemd:
        scope: user
        daemon_reload: yes
        state: restarted
        enabled: yes
        name: alok
