- hosts: 127.0.0.1
  connection: local
  become: true
  gather_facts: no
  tasks:
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - /usr/share/alok
        - /var/log/alok
    - name: Copy alok.jar to /usr/share/alok
      copy:
        src: ../target/alok-1.0-SNAPSHOT-jar-with-dependencies.jar
        dest: /usr/share/alok/alok.jar
        mode: "0644"
    - name: Create alok systemd service
      copy:
        src: alok.service
        dest: /etc/systemd/system/alok.service
    - name: Enable & (re)start alok service
      systemd:
        daemon_reload: yes
        state: restarted
        enabled: yes
        name: alok
